name: dotfiles
version: 0.0.1
description: Provides a simple mechanism for tracking all of your linux configuration files like ~/.bashrc with git.
environment: 
  sdk: '>=2.19.0 <3.0.0'
dependencies: 
  args: ^2.3.1
  dcli: 2.0.1
  dcli_core: 2.0.1
  http: ^0.13.4
  path: ^1.8.1
  settings_yaml: ^5.0.0-beta.1
dev_dependencies: 
  lint_hard: ^2.0.0
executables: 
  dotfiles: 
